package com.chatcui.gateway.auth.model;

public enum AuthFailureCode {
    AUTH_V1_MISSING_CREDENTIAL,
    AUTH_V1_INVALID_SIGNATURE,
    AUTH_V1_TIMESTAMP_OUT_OF_WINDOW,
    AUTH_V1_REPLAY_DETECTED,
    AUTH_V1_COOLDOWN_ACTIVE,
    AUTH_V1_CREDENTIAL_DISABLED,
    AUTH_V1_PERMISSION_DENIED
}

